version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-api
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - url-shortener
    env_file:
      - ./.env

networks:
  url-shortener: